package main

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"pgregory.net/rapid"
)

// TestTraceIDRoundTrip はTrace IDのラウンドトリップを検証するProperty Based Test
func TestTraceIDRoundTrip(t *testing.T) {
	// Property 1: [A-Za-z0-9\-_] のみからなる長さ1〜64文字のTrace IDをランダム生成する
	rapid.Check(t, func(t *rapid.T) {
		// 有効なTrace IDをランダム生成 (1〜64文字、[A-Za-z0-9\-_])
		traceID := rapid.StringMatching(`^[A-Za-z0-9\-_]{1,64}$`).Draw(t, "trace_id")

		// X-Trace-ID ヘッダーとして /health に送信する
		req := httptest.NewRequest(http.MethodGet, "/health", nil)
		req.Header.Set("X-Trace-ID", traceID)
		recorder := httptest.NewRecorder()

		TraceIDMiddleware(http.HandlerFunc(HealthHandler)).ServeHTTP(recorder, req)

		// レスポンスヘッダー X-Trace-ID が、送信した値と完全に一致することを検証する
		got := recorder.Header().Get("X-Trace-ID")
		if got != traceID {
			t.Fatalf("X-Trace-ID mismatch: got %q, want %q", got, traceID)
		}
	})
}

// TestInvalidTraceIDRejected は不正なTrace IDが拒否されることを検証するProperty Based Test
func TestInvalidTraceIDRejected(t *testing.T) {
	// Feature: network-fault-observation, Property 2: 不正 Trace ID の拒否
	rapid.Check(t, func(t *rapid.T) {
		invalidTraceID := rapid.OneOf(
			rapid.StringMatching(`^[A-Za-z0-9\-_]{65,96}$`),
			rapid.StringMatching(`^[A-Za-z0-9\-_]{0,32}[!@#$%^&*()+=./:;?][A-Za-z0-9\-_]{0,32}$`),
		).Draw(t, "invalid_trace_id")

		req := httptest.NewRequest(http.MethodGet, "/health", nil)
		req.Header.Set("X-Trace-ID", invalidTraceID)
		recorder := httptest.NewRecorder()

		TraceIDMiddleware(http.HandlerFunc(HealthHandler)).ServeHTTP(recorder, req)

		if recorder.Code != http.StatusBadRequest {
			t.Fatalf("status code = %d, want %d for Trace ID %q", recorder.Code, http.StatusBadRequest, invalidTraceID)
		}
	})
}

// TestAllRequestsLogged は全リクエストがログに記録されることを検証するProperty Based Test
func TestAllRequestsLogged(t *testing.T) {
	// Feature: network-fault-observation, Property 3: 全リクエストに対するログ記録
	rapid.Check(t, func(t *rapid.T) {
		// HTTPメソッドとパスの組み合わせをランダム生成する
		method := rapid.OneOf(
			rapid.Just("GET"),
			rapid.Just("POST"),
			rapid.Just("PUT"),
			rapid.Just("DELETE"),
		).Draw(t, "method")

		path := rapid.OneOf(
			rapid.Just("/health"),
			rapid.Just("/api/users"),
			rapid.Just("/api/items"),
			rapid.Just("/api/data"),
		).Draw(t, "path")

		// キャプチャ用のログエントリを保存する変数
		var capturedLog *LogEntry

		// テスト用ロガーを設定
		testLogger := &testLogger{
			captured: &capturedLog,
		}
		oldLogger := logWriter
		SetLogger(testLogger)
		defer SetLogger(oldLogger)

		// 生成したリクエストを既存の TraceIDMiddleware 的方式来処理する
		req := httptest.NewRequest(method, path, nil)
		recorder := httptest.NewRecorder()

		TraceIDMiddleware(http.HandlerFunc(HealthHandler)).ServeHTTP(recorder, req)

		// 1リクエストにつきログが記録されることを確認する
		if capturedLog == nil {
			t.Fatalf("no log entry recorded for request %s %s", method, path)
		}

		// ログに少なくとも trace_id, method, path, status が含まれることを検証する
		if capturedLog.TraceID == "" {
			t.Fatalf("log entry missing trace_id")
		}
		if capturedLog.Method == "" {
			t.Fatalf("log entry missing method")
		}
		if capturedLog.Path == "" {
			t.Fatalf("log entry missing path")
		}
		if capturedLog.Status == 0 {
			t.Fatalf("log entry missing status")
		}

		// 生成した method と path がログの値と一致することも検証する
		if capturedLog.Method != method {
			t.Fatalf("log method = %q, want %q", capturedLog.Method, method)
		}
		if capturedLog.Path != path {
			t.Fatalf("log path = %q, want %q", capturedLog.Path, path)
		}
	})
}

// TestMissingTraceIDAutoGenerated はTrace ID未指定時の自動生成を検証するProperty Based Test
func TestMissingTraceIDAutoGenerated(t *testing.T) {
	// Feature: network-fault-observation, Property 4: 空 Trace ID のときの自動生成
	var capturedLog *LogEntry
	oldLogger := logWriter
	SetLogger(&testLogger{captured: &capturedLog})
	t.Cleanup(func() { SetLogger(oldLogger) })

	rapid.Check(t, func(t *rapid.T) {
		requestCount := rapid.IntRange(2, 10).Draw(t, "request_count")

		for i := 0; i < requestCount; i++ {
			req := httptest.NewRequest(http.MethodGet, "/health", nil)
			recorder := httptest.NewRecorder()

			TraceIDMiddleware(http.HandlerFunc(HealthHandler)).ServeHTTP(recorder, req)

			traceID := TraceID(recorder.Header().Get("X-Trace-ID"))
			if traceID == "" {
				t.Fatalf("request %d: response header X-Trace-ID is empty", i)
			}
			if !traceID.Validate() {
				t.Fatalf("request %d: generated Trace ID %q is invalid", i, traceID)
			}
		}
	})
}

// testLogger はテスト用のロガー
type testLogger struct {
	captured **LogEntry
}

func (l *testLogger) WriteLog(e LogEntry) {
	*l.captured = &e
}
